### ISSUE TITLE
Extend 'use' to server too

### ISSUE THREAD

**Issue by dearlordylord** [dgellow/meteor-react-loader#1]
Hey,

is there reason to export this component on client only? (`api.use('reactjs:react@0.2.1', 'client');`)

I wrote some react packages recently too and it seems exporting it to server looks well too (see https://github.com/Firfi/tcomb-form-meteor/blob/master/package.js)

I do it just in the case if eventually I'll want (and on some stage of project I will) server-side rendering for search engines.

**Comment by dgellow** [comment]
@Firfi Not a particular reason. I just didn't think about server-side rendering.
Thanks for pointing out the problem.

**Comment by dgellow** [comment]
The pull request #3 fixed the issue #2 (error on startup) but the module is now only exported to the client.
I reopen this issue.
