### ISSUE TITLE
Latest freshly installed version (0.0.4) gives an error on startup

### ISSUE THREAD

**Issue by dearlordylord** [dgellow/meteor-react-loader#2]
20150423-02:35:41.421(7)? (STDERR) ReferenceError: document is not defined
W20150423-02:35:41.421(7)? (STDERR)     at createEl (packages/dgellow:react-loader/.npm/package/node_modules/react-loader/node_modules/spin.js/spin.js:28:1)

**Comment by dgellow** [comment]
Hi @Firfi .
Thank you for the feedback, I will check the issue this week.
Sorry for the late reply.
